import test from 'node:test';
import Image from 'next/image';
import {
  getCartbySessionId,
  getCartsFromSql,
  getnunberOfItemsInCartBySessionId,
} from '../../database/CardsControler';
import { getItemById } from '../../database/psotgersControler';
import { getCookie } from '../../util/cookies';
import { SessionIdManager } from '../../util/SessionIdManger';
import CartPageForm from './cartPageFrom';

export const metadata = {
  title: 'Cart page ',
  description: 'Generated by create next app',
};

export default async function CartPage() {
  const sessionID = await SessionIdManager(); // get session id
  const cartItems = await getCartsFromSql(); // get all cart items
  const cartItemsPerSession = cartItems.filter(function (value) {
    return value.sessionId === sessionID; // get cart items for sessionID
  });

  let items = []; // get all itemIds from cart items
  cartItemsPerSession.map(async (item) => {
    items.push(item.itemId);
  });

  return (
    <main>
      <h1> Cart Page </h1>
      <p> {sessionID} </p>

      <CartPageForm />
    </main>
  );
}
