import { cookies } from 'next/headers';
import Image from 'next/image';
import { getItem } from '../../database/items.js';
import { getItemById, getItemsByIdS } from '../../database/psotgersControler';
import { getCookie } from '../../util/cookies.ts';
import CartPageForm from './cartPageFrom.js';

export const metadata = {
  title: 'Cart page ',
  description: 'Generated by create next app',
};

export default function cartPage() {
  // const cookieStore = cookies();
  // const itemCart = cookieStore.get('itemCart');
  //  const item = getItem(1);
  const getCookieValue = getCookie('itemCart');
  /// const getItemCart = cookies().getAll('itemCart');
  // const itemCart = getItemCart;
  // const regex = /\d+(?=})/gm;
  // const itemsid = regex.exec(JSON.stringify(itemCart));
  // const item = getItemById(Number(itemsid));
  const items = getItemsByIdS(Number(getCookieValue));
  return (
    <main>
      <h1>Yor Itmes </h1>
      <p> {items.id} </p>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            {' '}
            <p>{item.itemName}</p>{' '}
          </li>
        ))}
      </ul>
    </main>
  );
}
