import test from 'node:test';
import Image from 'next/image';
import {
  getCartbySessionId,
  getCartsFromSql,
  getnunberOfItemsInCartBySessionId,
} from '../../database/CardsControler';
import { getItemById } from '../../database/psotgersControler';
import { getCookie } from '../../util/cookies';
import { SessionIdManager } from '../../util/SessionIdManger';
import CartPageForm from './cartPageFrom';

export const metadata = {
  title: 'Cart page ',
  description: 'Generated by create next app',
};

export default async function CartPage() {
  const sessionID = await SessionIdManager(); // get session id
  const cartItems = await getCartsFromSql(); // get all cart items
  const cartItemsPerSession = cartItems.filter(function (value) {
    return value.sessionId === sessionID; // get cart items for sessionID
  });

  const items = []; // get all itemIds from cart items
  await Promise.all(
    cartItemsPerSession.map(async (item) => {
      items.push(await getItemById(item.itemId));
    }),
  );

  return (
    <main>
      <h1> Cart Page </h1>
      <p> {sessionID} </p>

      <ul>
        {items.map((item) => (
          <li key={item.id}>
            <h2> {item.itemName} </h2>
            <p> {item.brand} </p>
            <p> {'price = ' + item.price + '€'} </p>
            <Image
              src={item.img}
              alt={item.itemName}
              unoptimized={true}
              width={255}
              height={340}
            />
            <p> {'Stock : ' + item.stock + ' .stk'} </p>
            <p> {item.description}</p>
          </li>
        ))}
      </ul>

      <CartPageForm />
    </main>
  );
}
