import Image from 'next/image';
import { getItemById } from '../../../database/psotgersControler';
import CartItemForm from './CartItemFrom';

export const metadata = {
  title: 'Items Page',
  description: 'Generated by create next app',
};

export default async function ItemPage(props) {
  const item = await getItemById(Number(props.params.Itemid));
  const itemId = Number(props.params.Itemid);
  const stock = Number(item.stock);

  return (
    <main>
      <h1> {item.itemName} </h1>
      <p> {item.brand} </p>
      <p> {'price = ' + item.price + '€'} </p>
      <Image
        src={item.img}
        alt={item.itemName}
        unoptimized={true}
        width={255}
        height={340}
      />
      <p> {'Stock : ' + item.stock + ' .stk'} </p>
      <p> {item.description}</p>

      <CartItemForm item={itemId} stock={stock} />
    </main>
  );
}
