import test from 'node:test';
import Image from 'next/image';
import Link from 'next/link';
import { createTables } from '../database/databaseSetup.js';
import { getItems } from '../database/items.js';
import {
  crateItem,
  deleteItem,
  getItemsFromSql,
} from '../database/psotgersControler';

export const metadata = {
  title: 'Mainpage  page',
  description: 'Generated by create next app',
};

export default async function Home() {
  const newItems = await getItemsFromSql();
  /// await crateItem('test01', 'test02', 100, 100, 'test03IMG', 'test04', 'testG');
  await deleteItem(20);
  // await createTables();

  // console.log(getItemsFromSql().then((resA) => console.log(resA)));
  // console.log(getItemsFromSql().then((rB) => console.log(rB)));

  return (
    <main>
      <h1> Bernhard Shop </h1>
      <p> Welcome to Bernhard's Shop</p>
      <h2>Our Products </h2>

      <ul>
        {newItems.map((newitem) => (
          <li key={`item.id ${newitem.id}`}>
            <Link href={`/Items/${newitem.id}`}>{newitem.itemName}</Link>
            <p> {newitem.brand} </p>

            <p> {'price = ' + newitem.price + '€'} </p>
            <Link href={`/Items/${newitem.id}`}>
              <Image
                src={newitem.img}
                alt={newitem.itemName}
                unoptimized={true}
                width={255}
                height={340}
              />
            </Link>
            <p> {'Stock : ' + newitem.stock + ' .stk'} </p>
            <p> {newitem.shortDescription} </p>
          </li>
        ))}
      </ul>
    </main>
  );
}
