export const metadata = {
  title: 'Thanks page ',
  description: 'Generated by create next app',
};

export default function ThanksPage() {
  return (
    <main>
      <div> Thanks for Shopping </div>
      <a href="/">Buy More</a>
    </main>
  );
}
