import Image from 'next/image';
import { getCartsFromSql } from '../../database/CardsControler';
import { getItemById } from '../../database/psotgersControler';
import { SessionIdManager } from '../../util/SessionIdManger';
import BuyForm from './BuyFrorm.js';

export const metadata = {
  title: 'Ceckout page ',
  description: 'Generated by create next app',
};

export default async function CheckoutPage() {
  const sessionID = await SessionIdManager(); // get session id
  const cartItems = await getCartsFromSql(); // get all cart items
  const cartItemsPerSession = cartItems.filter(function (value) {
    return value.sessionId === sessionID; // get cart items for sessionID
  });

  const items = []; // get all itemIds from cart items
  await Promise.all(
    cartItemsPerSession.map(async (item) => {
      items.push(await getItemById(item.itemId));
    }),
  );

  return (
    <main>
      <form>
        <ul>
          <li>
            <label>
              First Name:
              <input name="todo" data-test-id="checkout-first-name" required />
            </label>
          </li>
          <li>
            <label>
              Last Name:
              <input name="todo" data-test-id="checkout-last-name" required />
            </label>
          </li>
          <li>
            <label>
              E-Mail:
              <input name="todo" required data-test-id="checkout-email" />
            </label>
          </li>
          <li>
            <label>
              Address:
              <input name="todo" required data-test-id="checkout-address" />
            </label>
          </li>
          <li>
            <label>
              City:
              <input name="todo" required data-test-id="checkout-city" />
            </label>
          </li>
          <li>
            <label>
              Postal Code:
              <input name="todo" required data-test-id="checkout-postal-code" />
            </label>
          </li>
          <li>
            <label>
              Country:
              <input name="todo" required data-test-id="checkout-country" />
            </label>
          </li>
          <li>
            <label>
              Credit Card:
              <input name="todo" required data-test-id="checkout-credit-card" />
            </label>
          </li>
          <li>
            <label>
              Expiration-Date:
              <input
                name="todo"
                required
                data-test-id="checkout-expiration-date"
              />
            </label>
          </li>
          <li>
            <label>
              Security Code:
              <input
                name="todo"
                required
                data-test-id="checkout-security-code"
              />
            </label>
          </li>
        </ul>
      </form>
      <h1>Yor Itmes </h1>
      <ul>
        {items.map((item) => (
          <li key={item.id}>
            <h2> {item.itemName} </h2>
            <p> {item.brand} </p>
            <p> {'price = ' + item.price + '€'} </p>
            <Image
              src={item.img}
              alt={item.itemName}
              unoptimized={true}
              width={255}
              height={340}
            />
            <p> {'Stock : ' + item.stock + ' .stk'} </p>
            <p> {item.description}</p>
          </li>
        ))}
      </ul>

      <BuyForm />
    </main>
  );
}
